language: java
jdk: oraclejdk8
sudo: required

addons:
  apt:
    packages:
    - glpk

install:
  true

script:
  mvn clean package

after_success:
  echo $SUCCESSMESSAGE

after_failure:
  echo $ERRORMESSAGE

notifications:
  email: true